apiVersion: v1
kind: Pod
metada:
  name: gateway-pod
  labels:
    app: gateway
    type: microservice
spec:
  containers:
    - name: gateway-app
      image: cesarin1339/serviciosapigateway:latest
      ports:
        - containerPort: 80