apiVersion: v1
kind: Pod
metada:
  name: microservice-seguridad-pod
  labels:
    app: microservice-seguridad
    type: microservice
spec:
  containers:
    - name: microservice-seguridad-app
      image: cesarin1339/serviciosapiseguridad:latest
      ports:
        - containerPort: 80
      env:
        - name: ConnectionStrings__ConexionDB
          value: Server=mssql-service;Database=Seguridad;User=sa;Password=$VaxiDrez2025
