apiVersion: v1
kind: Pod
metada:
  name: mssql-pod
  labels:
    app: microservice-seguridad
    type: mssql-pod
spec:
  containers:
    - name: mssql
      image: mcr.microsoft.com/mssql/server
      ports:
        - containerPort: 1443
      env:
      - name: ACCEPT_EULA
        value: "Y"
      - name: SA_PASSWORD
        value: "$VaxiDrez2025"
