apiVersion: v1
kind: Service
metadata:
  name: mssql-service
  labels:
    name: mssql-service
    app: database
spec:
  type: LoadBalancer
  ports:
    - port: 1443
      targetPort: 1443
  selector:
    app: microservice-seguridad
    type: mssql-pod